# Generated by Django 3.2.13 on 2022-05-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('sentence', models.TextField()),
                ('cur_state', models.CharField(max_length=64)),
                ('condition', models.CharField(max_length=1024)),
                ('new_state', models.CharField(max_length=64)),
            ],
        ),
    ]
