# Generated by Django 3.2.13 on 2022-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('sentence', models.TextField()),
                ('cur_state', models.CharField(max_length=64)),
                ('event', models.CharField(max_length=1024)),
                ('new_state', models.CharField(max_length=64)),
            ],
        ),
    ]
